reload "user.plugins"
reload "user.options"
reload "user.keymaps"
reload "user.autocommands"
reload "user.lsp.init"

-- Individual plugins
reload "user.git"
reload "user.treesitter"
reload "user.tagbar"
reload "user.whichkey"
reload "user.toggleterm"
reload "user.nvimdap"
reload "user.luasnip"
reload "user.nvim-surround.nvim-surround"
reload "user.prettier"
